# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    blacklistedKernelModules = [
    ];

    extraModprobeConfig = ''
      options cfg80211 ieee80211_regdom="US"
    '';
    extraModulePackages = [ ];

    initrd = {
      # availableKernelModules = [ "zfs" ];
      supportedFilesystems = [ "zfs" ];
    };

    kernelModules = [
      "amdgpu"
      "kvm-amd"
      "zfs"
    ];

    supportedFilesystems = [ "zfs" ];
  };

  fileSystems."/" = {
    device = "tank0/root";
    fsType = "zfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/D62D-1688";
    fsType = "vfat";
  };

  swapDevices = [
    {
      device = "/dev/disk/by-uuid/21595e8b-385c-49f5-915d-1e7080b4a192";
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  networking.hostId = "0cc01337";
  # networking.interfaces.wlp170s0.useDHCP = lib.mkDefault true;

  lib.stdenv.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.amdgpu = {
    initrd.enable = true;
    opencl.enable = true;
    overdrive = {
      enable = true;
      ppfeaturemask = "0xffffffff";
    };
  };
  hardware.cpu.amd.updateMicrocode = true;
  hardware.enableAllFirmware = true;

  services.fwupd.enable = true;
  services.lact = {
    enable = true;
  };
}
