# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    blacklistedKernelModules = [
    ];

    extraModprobeConfig = ''
      options cfg80211 ieee80211_regdom="US"
    '';
    extraModulePackages = [ ];

    initrd = {
      availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "uas" "sd_mod" ];
      kernelModules = [ ];

      # Both LUKS volumes must open in initrd: root to mount, swap to
      # resume from hibernation (see boot.resumeDevice in configuration.nix).
      luks.devices = {
        "luks-c4ba12bd-9720-49e9-9e76-b53c9cf759b3".device = "/dev/disk/by-uuid/c4ba12bd-9720-49e9-9e76-b53c9cf759b3";
        "luks-6fa51307-36e9-48a7-89f2-daef74f125a7".device = "/dev/disk/by-uuid/6fa51307-36e9-48a7-89f2-daef74f125a7";
      };
    };

    kernelModules = [
      "amdgpu"
      "kvm-amd"
    ];
  };

  fileSystems."/" = {
    device = "/dev/mapper/luks-c4ba12bd-9720-49e9-9e76-b53c9cf759b3";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/60E6-2929";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [
    {
      device = "/dev/mapper/luks-6fa51307-36e9-48a7-89f2-daef74f125a7";
    }
  ];
  networking.useDHCP = lib.mkDefault true;

  lib.stdenv.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.amdgpu = {
    initrd.enable = true;
    opencl.enable = true;
    overdrive = {
      enable = true;
      ppfeaturemask = "0xffffffff";
    };
  };
  hardware.cpu.amd.updateMicrocode = true;
  hardware.enableAllFirmware = true;

  services.fwupd.enable = true;
  services.lact = {
    enable = true;
  };
}
