{ ... }:
# Espresso 15 Pro: route its touch + pen input to its own panel.
#
# The display's digitizer reports USB id 056a:0529 (Wacom ISDv4). Two issues
# have to be corrected together:
#
# 1. libwacom ships a generic 056a:0529 entry (autogenerated from a Wimaxit
#    portable monitor) flagged `IntegratedIn=Display;System`. The `System` flag
#    makes GNOME treat the digitizer as the laptop's *built-in* panel and bind
#    input to eDP, overriding any output mapping. The override below drops
#    `System` so GNOME treats it as an external display tablet (Cintiq-style).
#
# 2. The pen and the finger touchscreen are *separate* input devices with
#    *separate* per-device output mappings. GNOME's "Map to Monitor" GUI only
#    touches the tablet (pen) key, so the finger touchscreen has to be mapped
#    explicitly too.
#
# Output is identified by the [vendor, product, serial] from the Espresso's
# EDID (connector-independent, so it survives plugging into a different port).
{
  xdg.configFile."libwacom/wacom-isdv4-0529.tablet".text = ''
    # Local override: drop IntegratedIn=System so GNOME treats the Espresso's
    # digitizer as an external display tablet, not the laptop's built-in panel.
    [Device]
    Name=Wacom ISDv4 0529
    ModelName=
    DeviceMatch=usb|056a|0529
    Class=ISDV4
    Width=6
    Height=4
    IntegratedIn=Display

    [Features]
    Stylus=true
    Touch=true
  '';

  dconf.settings = {
    "org/gnome/desktop/peripherals/touchscreens/056a:0529" = {
      output = [ "ESP" "eD15P(2024)" "0x00012690" ];
    };
    "org/gnome/desktop/peripherals/tablets/056a:0529" = {
      output = [ "ESP" "eD15P(2024)" "0x00012690" ];
    };
  };
}
